# Generated by Django 3.1.4 on 2021-01-13 07:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Mi Habilidad',
                'verbose_name_plural': 'Habilidades de los empleados',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='Nombres completos')),
                ('job', models.CharField(choices=[('0', 'Ayudante General'), ('1', 'Supervisor'), ('2', 'Encargado'), ('3', 'Contador'), ('4', 'Proveedor'), ('5', 'Director General')], max_length=50, verbose_name='Trabajo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='empleado')),
                ('hoja_vida', ckeditor.fields.RichTextField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamento.departamento')),
                ('habilidades', models.ManyToManyField(to='Empleado.Habilidades')),
            ],
            options={
                'verbose_name': 'Mi Empleado',
                'verbose_name_plural': 'Empleados de la empresa',
                'ordering': ['-first_name'],
            },
        ),
    ]
