# Generated by Django 3.0 on 2020-07-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Empleado', '0002_auto_20200701_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='Empleado.Habilidades'),
        ),
    ]
